In [91]:
import pandas as pd
import numpy as np 
import re

In [92]:
df = pd.read_csv("DataScrape1v2_cpsc329.csv")

In [93]:
df

,Entity,Year,Records,Organization type,Method,Sources
0,50 companies and government institutions,2022,"6,400,000",various,poor security,[114][115]
1,21st Century Oncology,2015,"2,200,000 customer's data, including names, So...",healthcare,hacked,[116][117][118]
2,23andMe,2023,"6,900,000",consumer genetics,credential stuffing,[119]
3,500px,2020,"14,870,304",social network,hacked,[120]
4,Accendo Insurance Co.,2020,"175,350",healthcare,poor security,[121][122]
...,...,...,...,...,...,...
336,Yahoo Japan,2013,"22,000,000","tech, web",hacked,[548]
337,Yahoo! Voices,2012,"450,000",web,hacked,[549][550]
338,YouTube,2020,"4,000,000",social network,poor security,[348]
339,Zappos,2012,"24,000,000",e-commerce,hacked,[551]
340,Zynga,2019,"173,000,000",social network,hacked,[552][553]

In [94]:
newdf = df.drop(columns= 'Sources')

In [95]:
newdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,"6,400,000",various,poor security
1,21st Century Oncology,2015,"2,200,000 customer's data, including names, So...",healthcare,hacked
2,23andMe,2023,"6,900,000",consumer genetics,credential stuffing
3,500px,2020,"14,870,304",social network,hacked
4,Accendo Insurance Co.,2020,"175,350",healthcare,poor security
...,...,...,...,...,...
336,Yahoo Japan,2013,"22,000,000","tech, web",hacked
337,Yahoo! Voices,2012,"450,000",web,hacked
338,YouTube,2020,"4,000,000",social network,poor security
339,Zappos,2012,"24,000,000",e-commerce,hacked
340,Zynga,2019,"173,000,000",social network,hacked

In [96]:
count_of_na = newdf.isna().sum()
count_of_na

Entity               0
Year                 0
Records              2
Organization type    6
Method               7
dtype: int64

In [133]:
newdf.duplicated().sum()
#zero duplicated values

0

In [97]:
def counts_stuff(col):
    count_of_string_values =  0
    count_of_folat_values = 0 
    for i in col:
        if isinstance(i,str):
            count_of_string_values +=1
        if isinstance(i,float): 
            count_of_folat_values +=1


    print ("Count of values that are considered floats: ",count_of_folat_values)
    print ("count of string values that are considered strings:", count_of_string_values)
    # as we can see all of the na values are considered floats, hence we need to drop them

counts_stuff(newdf['Records'])

Count of values that are considered floats:  2
count of string values that are considered strings: 339

In [98]:
cleanednewdf = newdf.dropna()

In [99]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,"6,400,000",various,poor security
1,21st Century Oncology,2015,"2,200,000 customer's data, including names, So...",healthcare,hacked
2,23andMe,2023,"6,900,000",consumer genetics,credential stuffing
3,500px,2020,"14,870,304",social network,hacked
4,Accendo Insurance Co.,2020,"175,350",healthcare,poor security
...,...,...,...,...,...
336,Yahoo Japan,2013,"22,000,000","tech, web",hacked
337,Yahoo! Voices,2012,"450,000",web,hacked
338,YouTube,2020,"4,000,000",social network,poor security
339,Zappos,2012,"24,000,000",e-commerce,hacked
340,Zynga,2019,"173,000,000",social network,hacked

In [100]:
counts_stuff(cleanednewdf['Records'])

Count of values that are considered floats:  0
count of string values that are considered strings: 334

In [101]:
cleanednewdf = cleanednewdf.replace(',','', regex=True)

In [102]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,6400000,various,poor security
1,21st Century Oncology,2015,2200000 customer's data including names Social...,healthcare,hacked
2,23andMe,2023,6900000,consumer genetics,credential stuffing
3,500px,2020,14870304,social network,hacked
4,Accendo Insurance Co.,2020,175350,healthcare,poor security
...,...,...,...,...,...
336,Yahoo Japan,2013,22000000,tech web,hacked
337,Yahoo! Voices,2012,450000,web,hacked
338,YouTube,2020,4000000,social network,poor security
339,Zappos,2012,24000000,e-commerce,hacked
340,Zynga,2019,173000000,social network,hacked

In [103]:
def convert_to_int_if_number(s):
    if bool(re.match(r'^\d{1,3}(,\d{3})*(\.\d+)?$|^\d+(\.\d+)?$', s)):
        # Remove commas and convert to int
        return int(s.replace(',', ''))
    return pd.NA

In [104]:
cleanednewdf['Records'] = cleanednewdf['Records'].apply(convert_to_int_if_number)

In [105]:
count_of_none_numbers = cleanednewdf.isna().sum()
count_of_none_numbers

Entity                0
Year                  0
Records              59
Organization type     0
Method                0
dtype: int64

In [106]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,6400000,various,poor security
1,21st Century Oncology,2015,<NA>,healthcare,hacked
2,23andMe,2023,6900000,consumer genetics,credential stuffing
3,500px,2020,14870304,social network,hacked
4,Accendo Insurance Co.,2020,175350,healthcare,poor security
...,...,...,...,...,...
336,Yahoo Japan,2013,22000000,tech web,hacked
337,Yahoo! Voices,2012,450000,web,hacked
338,YouTube,2020,4000000,social network,poor security
339,Zappos,2012,24000000,e-commerce,hacked
340,Zynga,2019,173000000,social network,hacked

In [107]:
cleanednewdf = cleanednewdf.dropna()

In [108]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,6400000,various,poor security
2,23andMe,2023,6900000,consumer genetics,credential stuffing
3,500px,2020,14870304,social network,hacked
4,Accendo Insurance Co.,2020,175350,healthcare,poor security
6,Adobe Systems Incorporated,2013,152000000,tech,hacked
...,...,...,...,...,...
336,Yahoo Japan,2013,22000000,tech web,hacked
337,Yahoo! Voices,2012,450000,web,hacked
338,YouTube,2020,4000000,social network,poor security
339,Zappos,2012,24000000,e-commerce,hacked
340,Zynga,2019,173000000,social network,hacked

In [109]:
cleanednewdf['Method'].unique()

array(['poor security', 'credential stuffing', 'hacked',
       'lost / stolen media', 'inside job hacked',
       'accidentally published (sometimes referred to as a "Data Valdez"[147][148][149] due to its size)',
       'accidentally published', 'lost / stolen computer', 'unknown',
       'unsecured S3 bucket', 'web scraping',
       'compilation of multiple data breaches', 'inside job',
       'misconfigured website', 'ransomware hacked', 'data misuse',
       'accidentally uploaded', 'hacked by ALPHV',
       'poor security / hacked', 'unprotected api',
       'poor security/inside job', 'data exposed by misconfiguration',
       'intentionally lost', 'misconfiguration/poor security',
       'rogue contractor', 'improper setting hacked', 'misconfigured API',
       'compromised credentials',
       'publicly accessible Amazon Web Services (AWS) server',
       'accidentally exposed', 'social engineering'], dtype=object)

In [110]:
def mark_as_lost(s):
    return 'lost' if 'lost' in s.lower() else s

cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_lost)

C:\Users\Hanzd\AppData\Local\Temp\ipykernel_46960\3308347747.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_lost)

In [111]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,6400000,various,poor security
2,23andMe,2023,6900000,consumer genetics,credential stuffing
3,500px,2020,14870304,social network,hacked
4,Accendo Insurance Co.,2020,175350,healthcare,poor security
6,Adobe Systems Incorporated,2013,152000000,tech,hacked
...,...,...,...,...,...
336,Yahoo Japan,2013,22000000,tech web,hacked
337,Yahoo! Voices,2012,450000,web,hacked
338,YouTube,2020,4000000,social network,poor security
339,Zappos,2012,24000000,e-commerce,hacked
340,Zynga,2019,173000000,social network,hacked

In [114]:
def mark_as_poor_security(s):
    return 'poor security' if 'poor security' in s.lower() else s

cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_poor_security)

C:\Users\Hanzd\AppData\Local\Temp\ipykernel_46960\2046235543.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_poor_security)

In [115]:
cleanednewdf

,Entity,Year,Records,Organization type,Method
0,50 companies and government institutions,2022,6400000,various,poor security
2,23andMe,2023,6900000,consumer genetics,credential stuffing
3,500px,2020,14870304,social network,hacked
4,Accendo Insurance Co.,2020,175350,healthcare,poor security
6,Adobe Systems Incorporated,2013,152000000,tech,hacked
...,...,...,...,...,...
336,Yahoo Japan,2013,22000000,tech web,hacked
337,Yahoo! Voices,2012,450000,web,hacked
338,YouTube,2020,4000000,social network,poor security
339,Zappos,2012,24000000,e-commerce,hacked
340,Zynga,2019,173000000,social network,hacked

In [117]:
def mark_as_accident(s):
    return 'accident' if 'accidentally' in s.lower() else s

cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_accident)

C:\Users\Hanzd\AppData\Local\Temp\ipykernel_46960\4139121329.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_accident)

In [118]:
cleanednewdf['Method'].unique()

array(['poor security', 'credential stuffing', 'hacked', 'lost',
       'inside job hacked', 'accident', 'unknown', 'unsecured S3 bucket',
       'web scraping', 'compilation of multiple data breaches',
       'inside job', 'misconfigured website', 'ransomware hacked',
       'data misuse', 'hacked by ALPHV', 'unprotected api',
       'data exposed by misconfiguration', 'rogue contractor',
       'improper setting hacked', 'misconfigured API',
       'compromised credentials',
       'publicly accessible Amazon Web Services (AWS) server',
       'social engineering'], dtype=object)

In [123]:
def mark_as_hacked(s):
    return 'hacked' if 'hacked' in s.lower() else s

cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_hacked)

C:\Users\Hanzd\AppData\Local\Temp\ipykernel_46960\3465952622.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanednewdf['Method'] = cleanednewdf['Method'].apply(mark_as_hacked)

In [127]:
cleanednewdf['Method'].value_counts()

Method
hacked                                                  158
poor security                                            39
lost                                                     32
inside job                                               13
accident                                                 11
unknown                                                   7
web scraping                                              2
misconfigured API                                         2
unsecured S3 bucket                                       1
compilation of multiple data breaches                     1
credential stuffing                                       1
misconfigured website                                     1
data misuse                                               1
unprotected api                                           1
data exposed by misconfiguration                          1
rogue contractor                                          1
compromised credentials                                   1
publicly accessible Amazon Web Services (AWS) server      1
social engineering                                        1
Name: count, dtype: int64

In [128]:
cleanednewdf['Organization type'].value_counts()

Organization type
web                                45
healthcare                         41
financial                          35
social network                     17
telecoms                           16
retail                             15
tech                               14
gaming                             14
e-commerce                          7
transport                           7
energy                              4
hotel/casino                        4
media                               4
telecommunications                  4
telecom                             3
restaurant                          3
online marketing                    3
tech retail                         2
dating                              2
educational services                2
genealogy                           2
various                             2
telephone directory                 1
ticket distribution                 1
market analysis                     1
consumer goods                      1
publisher (magazine)                1
military                            1
phone accessories                   1
web gaming                          1
question & answer                   1
clinical laboratory                 1
QR code payment                     1
food                                1
nonprofit financial                 1
financial credit bureau             1
local search                        1
shopping                            1
humanitarian                        1
automotives                         1
data broker                         1
computer services for charities     1
healthcare retail                   1
consumer genetics                   1
charity                             1
printing                            1
hosting provider                    1
healthcare pharmacy                 1
background check                    1
advertising                         1
tech web                            1
Name: count, dtype: int64

In [130]:
def mark_as_telecom(s):
    return 'telecom' if 'telecom' in s.lower() else s

cleanednewdf['Organization type'] = cleanednewdf['Organization type'].apply(mark_as_telecom)

C:\Users\Hanzd\AppData\Local\Temp\ipykernel_46960\2229809075.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanednewdf['Organization type'] = cleanednewdf['Organization type'].apply(mark_as_telecom)

In [129]:
cleanednewdf['Entity'].value_counts()

Entity
Facebook                      6
AT&T                          3
Citigroup                     3
AOL                           3
Countrywide Financial Corp    2
                             ..
Friend Finder Network         1
Funimation                    1
Formspring                    1
Gamigo                        1
Zynga                         1
Name: count, Length: 255, dtype: int64

In [134]:
cleanednewdf.to_csv(r'C:\Users\Hanzd\Desktop\CPSC 329\cleanedprojectdata_cpsc329.csv', index = False)

In [ ]:
''' 
The purpose of this was to create general categories for the data,
to make it make it more simple to clean the data and to model the data a bit better.
'''